// src/components/products.js
import { FiEye } from "react-icons/fi";

export let OfficeProducts = [
  {
    id: 1,
    title: "OfficeJet Pro 8135e Wireless All-in-One Printer",
    description:
      "Transform your home workspace with America's most trusted printer brand. Perfect for productivity, scanning and wireless printing.",
    image:
      "https://www.networkhardwares.com/cdn/shop/products/1079530649.jpg?v=1705589963&width=1000",
    images: [
      "https://www.networkhardwares.com/cdn/shop/products/1079530649.jpg?v=1705589963&width=1000",
      "https://images.hp.com/is/image/hpnewsroom/HP_OfficeJet_Pro_8000_Series?$large$",
      "https://images.hp.com/is/image/hp/officejetpro-8000-top?$large$",
      "https://images.hp.com/is/image/hp/officejetpro-8000-side?$large$",
      "https://images.hp.com/is/image/hp/officejetpro-8000-back?$large$",
      "https://images.hp.com/is/image/hp/officejetpro-8000-angle?$large$",
      "https://hp.widen.net/content/muwpvnq8dp/webp/muwpvnq8dp.png?w=573&h=430&dpi=72&color=ffffff00",
      "https://images.hp.com/is/image/hp/envy-7955e-1?$large$",
      "https://images.hp.com/is/image/hp/envy-7955e-2?$large$",
      "https://images.hp.com/is/image/hp/envy-7955e-3?$large$",
      "https://images.hp.com/is/image/hp/envy-7955e-4?$large$",
      "https://images.hp.com/is/image/hp/envy-7955e-5?$large$",
    ],
    price: 159.99,
    rating: 4.4,
    reviewsCount: 200,
    category: "home-printer",
    delivery: "2-3 business days delivery",

    highlights: [
      "Color inkjet printing for documents & photos",
      "Flatbed scanner with easy copy",
      "Wireless & mobile printing",
      "Quiet mode for home use",
      "Smart app setup in minutes",
    ],
    boxItems: [
      "All-in-One Printer",
      "Setup cartridges (Black & Color)",
      "Power cord",
      "USB cable",
      "Setup guide / documentation",
    ],
    specs: {
      "Print Technology": "Color Inkjet",
      "Max Print Resolution": "4800 × 1200 dpi",
      "Black Print Speed": "Up to 15 ppm",
      "Color Print Speed": "Up to 10 ppm",
      Scanner: "Flatbed up to 1200 dpi",
      Connectivity: "Wi-Fi, Wi-Fi Direct, USB",
      "Mobile Print": "AirPrint, Mopria, HP Smart App",
      "Paper Handling": "125-sheet input, 25-sheet output",
      Duplex: "Automatic (Print)",
      "Dimensions (W×D×H)": "18.1 × 14.2 × 9.2 in",
      Weight: "15.1 lb",
    },
    compatibility: [
      "Windows 11/10 (64-bit)",
      "macOS 12+",
      "ChromeOS",
      "iOS / iPadOS",
      "Android",
    ],
  },

  {
    id: 5,
    title: "HP OfficeJet Pro 9015e All-in-One Printer",
    description:
      "Smart, fast, and efficient wireless color inkjet printer for home office and small business needs.",
    image:
      "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/5/3/53N94C-1_T1705462958.png",
    images: [
      "https://hp.widen.net/content/abxnm7602o/webp/abxnm7602o.png?w=573&h=430&dpi=72&color=ffffff00",
      "https://images.hp.com/is/image/hp/officejetpro-9015e-1?$large$",
      "https://images.hp.com/is/image/hp/officejetpro-9015e-2?$large$",
      "https://images.hp.com/is/image/hp/officejetpro-9015e-3?$large$",
      "https://images.hp.com/is/image/hp/officejetpro-9015e-4?$large$",
      "https://images.hp.com/is/image/hp/officejetpro-9015e-5?$large$",
    ],
    price: 229.99,
    rating: 4.5,
    reviewsCount: 2100,
    category: "inkjet-printer",
    delivery: "2-4 business days delivery",

    highlights: [
      "Fast color prints for home office",
      "Auto 2-sided printing & scanning",
      "Robust ADF for multi-page jobs",
      "Wi-Fi + USB + Cloud print",
      "Low cost per page with XL cartridges",
    ],
    boxItems: [
      "OfficeJet Pro printer",
      "Setup cartridges",
      "Power cord",
      "USB cable",
      "Setup guide / docs",
    ],
    specs: {
      "Print Technology": "Color Inkjet",
      "Max Print Resolution": "4800 × 1200 dpi",
      "Black Print Speed": "Up to 22 ppm",
      "Color Print Speed": "Up to 18 ppm",
      Scanner: "Flatbed + 35-sheet ADF",
      Connectivity: "Wi-Fi, Wi-Fi Direct, USB, Ethernet",
      "Mobile Print": "AirPrint, Mopria, HP Smart App",
      "Paper Handling": "250-sheet input, 60-sheet output",
      Duplex: "Auto (Print/Scan)",
      "Dimensions (W×D×H)": "17.3 × 13.5 × 10.9 in",
      Weight: "20.3 lb",
    },
    compatibility: ["Windows 11/10", "macOS 12+", "ChromeOS", "iOS / Android"],
  },

  {
    id: 6,
    title: "HP LaserJet Pro M404dn",
    description:
      "Reliable and fast monochrome laser printer designed for high-volume office printing.",
    image:
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06288639.png",
    images: [
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06288639.png",
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06288640.png",
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06288641.png",
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06288642.png",
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06288643.png",
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06288644.png",
    ],
    price: 249.99,
    rating: 4.6,
    reviewsCount: 1800,
    category: "laser-printer",
    delivery: "2-4 business days delivery",

    highlights: [
      "Enterprise-grade mono laser",
      "Sharp text at high speeds",
      "Auto 2-sided printing",
      "Network-ready (Ethernet) + USB",
      "Built for reliability & heavy duty cycle",
    ],
    boxItems: [
      "Laser printer",
      "Introductory toner cartridge",
      "Power cord",
      "USB cable",
      "Documentation",
    ],
    specs: {
      "Print Technology": "Mono Laser",
      "Max Print Resolution": "1200 × 1200 dpi",
      "Black Print Speed": "Up to 40 ppm",
      "Color Print Speed": "—",
      Scanner: "— (print only)",
      Connectivity: "USB, Ethernet (model dependent)",
      "Mobile Print": "AirPrint, Mopria",
      "Paper Handling": "250-sheet input, 150-sheet output",
      Duplex: "Automatic (Print)",
      "Dimensions (W×D×H)": "15.0 × 14.0 × 8.5 in",
      Weight: "18.9 lb",
    },
    compatibility: ["Windows 11/10", "macOS 12+", "ChromeOS"],
  },

  {
    id: 7,
    title: "HP DeskJet 2755e Wireless Color Inkjet Printer",
    description:
      "Affordable wireless color printer for everyday home printing, scanning, and copying needs.",
    image:
      "https://owp.klarna.com/product/640x640/3044149769/HP-DeskJet-4222e-All-in-One-Drucker.jpg?ph=true",
    images: [
      "https://owp.klarna.com/product/640x640/3044149769/HP-DeskJet-4222e-All-in-One-Drucker.jpg?ph=true",
      "https://images.hp.com/is/image/hp/deskjet-2755e-1?$large$",
      "https://images.hp.com/is/image/hp/deskjet-2755e-2?$large$",
      "https://images.hp.com/is/image/hp/deskjet-2755e-3?$large$",
      "https://images.hp.com/is/image/hp/deskjet-2755e-4?$large$",
      "https://images.hp.com/is/image/hp/deskjet-2755e-5?$large$",
    ],
    price: 84.99,
    rating: 4.3,
    reviewsCount: 1800,
    category: "inkjet-printer",
    delivery: "2-4 business days delivery",

    highlights: [
      "Budget-friendly color printing",
      "Flatbed scan & copy",
      "Wireless + mobile printing",
      "Compact and easy to set up",
      "Ideal for schoolwork & home docs",
    ],
    boxItems: [
      "All-in-One Printer",
      "Setup cartridges",
      "Power cord",
      "USB cable",
      "Setup guide / documentation",
    ],
    specs: {
      "Print Technology": "Color Inkjet",
      "Max Print Resolution": "4800 × 1200 dpi",
      "Black Print Speed": "Up to 7.5 ppm",
      "Color Print Speed": "Up to 5.5 ppm",
      Scanner: "Flatbed up to 1200 dpi",
      Connectivity: "Wi-Fi, Wi-Fi Direct, USB",
      "Mobile Print": "AirPrint, Mopria, HP Smart App",
      "Paper Handling": "60-sheet input, 25-sheet output",
      Duplex: "Manual",
      "Dimensions (W×D×H)": "16.7 × 11.9 × 6.1 in",
      Weight: "7.5 lb",
    },
    compatibility: ["Windows 11/10", "macOS 12+", "ChromeOS", "iOS / Android"],
  },

  {
    id: 8,
    title: "HP ENVY Inspire 7955e All-in-One Printer",
    description:
      "Versatile and family-friendly inkjet printer designed for daily home use, with wireless and mobile printing.",
    image:
      "https://hp.widen.net/content/muwpvnq8dp/webp/muwpvnq8dp.png?w=573&h=430&dpi=72&color=ffffff00",
    images: [
      "https://hp.widen.net/content/muwpvnq8dp/webp/muwpvnq8dp.png?w=573&h=430&dpi=72&color=ffffff00",
      "https://images.hp.com/is/image/hp/envy-7955e-1?$large$",
      "https://images.hp.com/is/image/hp/envy-7955e-2?$large$",
      "https://images.hp.com/is/image/hp/envy-7955e-3?$large$",
      "https://images.hp.com/is/image/hp/envy-7955e-4?$large$",
      "https://images.hp.com/is/image/hp/envy-7955e-5?$large$",
    ],
    price: 159.99,
    rating: 4.4,
    reviewsCount: 200,
    category: "inkjet-printer",
    delivery: "2-4 business days delivery",

    highlights: [
      "All-in-One color inkjet for families",
      "Borderless photo printing",
      "Wireless + mobile printing",
      "Smart app guided setup",
      "Auto 2-sided printing",
    ],
    boxItems: [
      "All-in-One Printer",
      "Setup cartridges (Black & Color)",
      "Power cord",
      "USB cable",
      "Setup guide",
    ],
    specs: {
      "Print Technology": "Color Inkjet",
      "Max Print Resolution": "4800 × 1200 dpi",
      "Black Print Speed": "Up to 15 ppm",
      "Color Print Speed": "Up to 10 ppm",
      Scanner: "Flatbed up to 1200 dpi",
      Connectivity: "Wi-Fi, Wi-Fi Direct, USB",
      "Mobile Print": "AirPrint, Mopria, HP Smart App",
      "Paper Handling": "125-sheet input, 25-sheet output",
      Duplex: "Automatic (Print)",
      "Dimensions (W×D×H)": "18.1 × 14.2 × 9.2 in",
      Weight: "15.1 lb",
    },
    compatibility: ["Windows 11/10", "macOS 12+", "ChromeOS", "iOS / Android"],
  },

  {
    id: 9,
    title: "HP 67XL High Yield Black Ink Cartridge",
    description:
      "Original HP black ink for sharp text. XL yield helps reduce cost per page.",
    image:
      "https://www.hp.com/ca-en/shop/Html/Merch/Images/c06351403_1750x1285.jpg",
    price: 32.99,
    rating: 4.7,
    reviewsCount: 412,
    delivery: "2–3 business days",
    brand: "HP",
    type: "ink",
    color: "black",
    pageYield: "XL ~400 pages",
    compatibleModels: ["DeskJet 2755e", "ENVY 6055e", "ENVY 6455e"],
  },
  {
    id: 10,
    title: "HP 67XL Tri-Color Ink Cartridge",
    description:
      "Original HP tri-color ink for vibrant photos and graphics. XL page yield.",
    image:
      "https://hp.widen.net/content/uaeyj14kx9/png/uaeyj14kx9.png?w=1659&h=1246&dpi=72&color=ffffff00",
    price: 34.99,
    rating: 4.6,
    reviewsCount: 289,
    delivery: "2–3 business days",
    brand: "HP",
    type: "ink",
    color: "tri-color",
    pageYield: "XL ~330 pages",
    compatibleModels: ["DeskJet 2755e", "ENVY 6055e", "ENVY 6455e"],
  },
  {
    id: 11,
    title: "HP 58A Black Toner Cartridge (CF258A)",
    description:
      "Reliable mono toner for LaserJet models. Crisp text and consistent results.",
    image:
      "https://i5.walmartimages.com/asr/452262cb-dd7a-4897-87fc-6a94991c18b6.a36e158aa1804ec24503309630129ab8.jpeg",
    price: 89.99,
    rating: 4.8,
    reviewsCount: 178,
    delivery: "2–3 business days",
    brand: "HP",
    type: "toner",
    color: "black",
    pageYield: "~3,000 pages",
    compatibleModels: ["LaserJet Pro M404", "LaserJet Pro M428"],
  },
  {
    id: 12,
    title: "Premium Inkjet & Laser Paper (500-sheet ream, 24 lb, Bright 98)",
    description:
      "Smooth, bright paper ideal for everyday color and mono documents.",
    image:
      "https://media.officedepot.com/images/f_auto,q_auto,e_sharpen,h_450/products/562903/562903_o01_24/562903",
    price: 11.49,
    rating: 4.5,
    reviewsCount: 102,
    delivery: "2–3 business days",
    brand: "Universal",
    type: "paper",
    pageYield: "—",
    compatibleModels: ["Inkjet & Laser printers (universal)"],
  },
  
  
];
